// 8x16 pixel patterns for large, readable digits and symbols
export const digitPatterns: { [key: string]: boolean[][] } = {
  '0': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '1': [
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, true, false, false, false],
    [false, true, true, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, true, true, false, false, false],
    [false, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, false],
    [false, false, false, false, false, false, false, false]
  ],
  '2': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, false, false]
  ],
  '3': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, true, true, true, false, false],
    [false, false, false, true, true, true, false, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '4': [
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, true, false],
    [false, false, false, true, true, true, true, false],
    [false, false, true, true, false, true, true, false],
    [false, true, true, false, false, true, true, false],
    [true, true, false, false, false, true, true, false],
    [true, true, false, false, false, true, true, false],
    [true, true, false, false, false, true, true, false],
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, false, false, false, false]
  ],
  '5': [
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, false, false],
    [true, true, true, true, true, true, true, false],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '6': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [true, true, true, true, true, true, false, false],
    [true, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '7': [
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, true, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '8': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, false, false, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, true, true, true, true, false, false],
    [false, true, true, false, false, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '9': [
    [false, false, true, true, true, true, false, false],
    [false, true, true, true, true, true, true, false],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, true],
    [false, false, true, true, true, true, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [false, false, false, false, false, false, true, true],
    [true, true, false, false, false, false, true, true],
    [false, true, true, true, true, true, true, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '%': [
    [true, true, true, false, false, false, false, true],
    [true, true, true, false, false, false, true, true],
    [true, true, true, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, false, false, false, false],
    [false, true, true, false, false, false, false, false],
    [true, true, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, true, true, false],
    [false, false, false, false, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [true, false, false, true, true, true, false, false],
    [true, true, false, true, true, true, false, false],
    [true, false, false, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '$': [
    [false, false, false, true, true, false, false, false],
    [false, false, true, true, true, true, true, false],
    [false, true, true, true, true, true, true, true],
    [true, true, false, true, true, false, false, false],
    [true, true, false, true, true, false, false, false],
    [false, true, true, true, true, false, false, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, true, true, true, true, false],
    [false, false, false, false, true, true, true, true],
    [false, false, false, false, true, true, false, true],
    [false, false, false, false, true, true, false, true],
    [true, true, false, false, true, true, false, true],
    [true, true, true, true, true, true, true, false],
    [false, true, true, true, true, true, false, false],
    [false, false, false, true, true, false, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  '.': [
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, true, true, true, true, false, false],
    [false, false, true, true, true, true, false, false],
    [false, false, true, true, true, true, false, false],
    [false, false, false, false, false, false, false, false]
  ],
  ' ': [
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, false, false, false, false]
  ]
};